apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-wheelers-deployment
  labels:
    app: two-wheelers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: two-wheelers
  template:
    metadata:
      labels:
        app: two-wheelers
    spec:
      containers:
      - name: two-wheelers
        image: 045486074202.dkr.ecr.us-east-1.amazonaws.com/shopping-site-two-wheelers:e8f19751dc4d3161519bef7dce0039c3abd12c71
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: two-wheelers-service
  labels:
    app: two-wheelers
spec:
  type: ClusterIP
  selector:
    app: two-wheelers
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
